name: T2A3 continuous integration

on: 
  push:
    branches: [ master ]

jobs:
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set Up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: pwd
        run: |
          ls
          pwd
      - name: change directory
        run: |
          cd src/
          pwd
          ls
      - name: print working directory
        run: | 
          pwd
      - name: Run Tests
        run: |
          python3 -m unittest discover Tests


